# Generated by Django 5.2.11 on 2026-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_address', models.TextField()),
                ('education_qualification', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('skill_set', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
